name: Node CI

on:
  push:
    branches:
      - master
      - 'v*' # prior release branches (e.g. `v0.30.x` branch)
    tags:
      - 'v*'
  pull_request:

jobs:
  discover_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v1
      - uses: rwjblue/setup-volta@v1
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - name: eslint
        run: for name in `ls packages/*/.eslintrc.js`; do dirname $name; done  | xargs npx eslint --
      - id: set-matrix
        working-directory: test-scenarios
        run: echo "::set-output name=matrix::$(npm run --silent test:list -- --matrix)"

  new_build:
    needs: discover_matrix
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.discover_matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v1
      - uses: rwjblue/setup-volta@v1
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - name: test
        run: ${{ matrix.command }}
        working-directory: ${{ matrix.dir }}

  # build:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       eai_scenario: [2.18, stable, beta, canary]
  #       suite:
  #         - 'cd packages/sample-direct      && npm run test'
  #         - 'cd packages/sample-direct      && npm run test'
  #         - 'cd packages/sample-direct      && npm run test:fastboot'
  #         - 'cd packages/sample-direct      && npm run test:prod'
  #         - 'cd packages/sample-direct      && npm run test:custom-bundles'
  #         - 'cd packages/sample-direct      && npm run test:custom-bundles-top'
  #         - 'cd packages/sample-direct      && npm run test:custom-bundles-fastboot'
  #         - 'cd packages/sample-direct      && npm run test:custom-csp'
  #         - 'cd packages/sample-indirect    && npm run test'
  #         - 'cd packages/sample-indirect    && npm run test:fastboot'
  #         - 'cd packages/sample-indirect    && npm run test:custom-csp'
  #         - 'cd packages/sample-addon       && npm run test'
  #         - 'cd packages/sample-failure     && npm run test'
  #         - 'cd packages/sample-merged      && npm run test'
  #         - 'cd packages/sample-conflict    && npm run test'
  #         - 'cd packages/sample-babel7      && npm run test'
  #         - 'cd packages/sample-typescript2 && npm run test'
  #         - 'cd packages/sample-typescript4 && npm run test'
  #         - 'cd packages/sample-noconflict  && npm run test'
  #         - 'cd packages/sample-noparse     && npm run test'
  #         - 'cd packages/ember-auto-import  && npm run test'
  #         - 'cd packages/sample-es-latest   && npm run test'
  #         - 'cd packages/sample-skip-babel  && npm run test'
  #         - 'cd packages/ember-auto-import  && npm run test:node'
  #       exclude:
  #         - suite: 'cd packages/sample-direct      && npm run test:custom-bundles'
  #           eai_scenario: 2.18
  #         - suite: 'cd packages/sample-direct      && npm run test:custom-bundles-top'
  #           eai_scenario: 2.18
  #         - suite: 'cd packages/sample-direct      && npm run test:custom-bundles-fastboot'
  #           eai_scenario: 2.18
  #       include:
  #         - suite: 'for name in `ls packages/*/.eslintrc.js`; do dirname $name; done  | xargs npx eslint --'
  #           eai_scenario: ''

  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: rwjblue/setup-volta@v1
  #       with:
  #         node-version: '14'
  #     - name: test
  #       run: ${{ matrix.suite }}
